services:

  postgres:
    image: postgres:17
    container_name: cx-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: cx_reply_assistant
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Root@123

    volumes:
      - postgres_data:/var/lib/postgresql/data

    ports:
      - "5432:5432"


  app:
    build: .
    container_name: cx-reply-assistant
    restart: unless-stopped

    depends_on:
      - postgres

    ports:
      - "8081:8081"

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/cx_reply_assistant
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Root@123

volumes:
  postgres_data: